# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b1a65bf45ee3d8c48d1aeed9435041b1241f7b082dbd0bf0ec9883d389302d90c08954eae7ff38437e25b2ac8ef98e8e656b43cb014155d2402c48f095da155

test:
  secret_key_base: b45464312568ca278f3af476250cdccb44ab038bb19eefa705696ea5f3f1524295d264b0529ef477fd91b15768dd7e60ab2b4d8ae4007f074d0c0fedc4ed8190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
